/* A\=B */
isDiff(prince_phillip, prince_charles).
isDiff(prince_phillip, captain_mark_phillips).
isDiff(prince_phillip, timothy_laurence).
isDiff(prince_phillip, prince_andrew).
isDiff(prince_phillip, prince_edward).
isDiff(prince_phillip, prince_william).
isDiff(prince_phillip, prince_harry).
isDiff(prince_phillip, peter_phillips).
isDiff(prince_phillip, mike_tindall).
isDiff(prince_phillip, james_viscount_severn).
isDiff(prince_phillip, prince_george).
isDiff(prince_phillip, queen_elizabeth_II).
isDiff(prince_phillip, princess_diana).
isDiff(prince_phillip, camilla_parker_bowles).
isDiff(prince_phillip, princess_anne).
isDiff(prince_phillip, sarah_ferguson).
isDiff(prince_phillip, sophie_rhys_jones).
isDiff(prince_phillip, kate_middleton).
isDiff(prince_phillip, autumn_kelly).
isDiff(prince_phillip, zara_phillips).
isDiff(prince_phillip, princess_beatrice).
isDiff(prince_phillip, princess_eugenie).
isDiff(prince_phillip, lady_louise_mountbatten_windsor).
isDiff(prince_phillip, princess_charlotte).
isDiff(prince_phillip, savannah_phillips).
isDiff(prince_phillip, isla_phillips).
isDiff(prince_phillip, mia_grace_tindall).
isDiff(prince_charles, prince_phillip).
isDiff(prince_charles, captain_mark_phillips).
isDiff(prince_charles, timothy_laurence).
isDiff(prince_charles, prince_andrew).
isDiff(prince_charles, prince_edward).
isDiff(prince_charles, prince_william).
isDiff(prince_charles, prince_harry).
isDiff(prince_charles, peter_phillips).
isDiff(prince_charles, mike_tindall).
isDiff(prince_charles, james_viscount_severn).
isDiff(prince_charles, prince_george).
isDiff(prince_charles, queen_elizabeth_II).
isDiff(prince_charles, princess_diana).
isDiff(prince_charles, camilla_parker_bowles).
isDiff(prince_charles, princess_anne).
isDiff(prince_charles, sarah_ferguson).
isDiff(prince_charles, sophie_rhys_jones).
isDiff(prince_charles, kate_middleton).
isDiff(prince_charles, autumn_kelly).
isDiff(prince_charles, zara_phillips).
isDiff(prince_charles, princess_beatrice).
isDiff(prince_charles, princess_eugenie).
isDiff(prince_charles, lady_louise_mountbatten_windsor).
isDiff(prince_charles, princess_charlotte).
isDiff(prince_charles, savannah_phillips).
isDiff(prince_charles, isla_phillips).
isDiff(prince_charles, mia_grace_tindall).
isDiff(captain_mark_phillips, prince_phillip).
isDiff(captain_mark_phillips, prince_charles).
isDiff(captain_mark_phillips, timothy_laurence).
isDiff(captain_mark_phillips, prince_andrew).
isDiff(captain_mark_phillips, prince_edward).
isDiff(captain_mark_phillips, prince_william).
isDiff(captain_mark_phillips, prince_harry).
isDiff(captain_mark_phillips, peter_phillips).
isDiff(captain_mark_phillips, mike_tindall).
isDiff(captain_mark_phillips, james_viscount_severn).
isDiff(captain_mark_phillips, prince_george).
isDiff(captain_mark_phillips, queen_elizabeth_II).
isDiff(captain_mark_phillips, princess_diana).
isDiff(captain_mark_phillips, camilla_parker_bowles).
isDiff(captain_mark_phillips, princess_anne).
isDiff(captain_mark_phillips, sarah_ferguson).
isDiff(captain_mark_phillips, sophie_rhys_jones).
isDiff(captain_mark_phillips, kate_middleton).
isDiff(captain_mark_phillips, autumn_kelly).
isDiff(captain_mark_phillips, zara_phillips).
isDiff(captain_mark_phillips, princess_beatrice).
isDiff(captain_mark_phillips, princess_eugenie).
isDiff(captain_mark_phillips, lady_louise_mountbatten_windsor).
isDiff(captain_mark_phillips, princess_charlotte).
isDiff(captain_mark_phillips, savannah_phillips).
isDiff(captain_mark_phillips, isla_phillips).
isDiff(captain_mark_phillips, mia_grace_tindall).
isDiff(timothy_laurence, prince_phillip).
isDiff(timothy_laurence, prince_charles).
isDiff(timothy_laurence, captain_mark_phillips).
isDiff(timothy_laurence, prince_andrew).
isDiff(timothy_laurence, prince_edward).
isDiff(timothy_laurence, prince_william).
isDiff(timothy_laurence, prince_harry).
isDiff(timothy_laurence, peter_phillips).
isDiff(timothy_laurence, mike_tindall).
isDiff(timothy_laurence, james_viscount_severn).
isDiff(timothy_laurence, prince_george).
isDiff(timothy_laurence, queen_elizabeth_II).
isDiff(timothy_laurence, princess_diana).
isDiff(timothy_laurence, camilla_parker_bowles).
isDiff(timothy_laurence, princess_anne).
isDiff(timothy_laurence, sarah_ferguson).
isDiff(timothy_laurence, sophie_rhys_jones).
isDiff(timothy_laurence, kate_middleton).
isDiff(timothy_laurence, autumn_kelly).
isDiff(timothy_laurence, zara_phillips).
isDiff(timothy_laurence, princess_beatrice).
isDiff(timothy_laurence, princess_eugenie).
isDiff(timothy_laurence, lady_louise_mountbatten_windsor).
isDiff(timothy_laurence, princess_charlotte).
isDiff(timothy_laurence, savannah_phillips).
isDiff(timothy_laurence, isla_phillips).
isDiff(timothy_laurence, mia_grace_tindall).
isDiff(prince_andrew, prince_phillip).
isDiff(prince_andrew, prince_charles).
isDiff(prince_andrew, captain_mark_phillips).
isDiff(prince_andrew, timothy_laurence).
isDiff(prince_andrew, prince_edward).
isDiff(prince_andrew, prince_william).
isDiff(prince_andrew, prince_harry).
isDiff(prince_andrew, peter_phillips).
isDiff(prince_andrew, mike_tindall).
isDiff(prince_andrew, james_viscount_severn).
isDiff(prince_andrew, prince_george).
isDiff(prince_andrew, queen_elizabeth_II).
isDiff(prince_andrew, princess_diana).
isDiff(prince_andrew, camilla_parker_bowles).
isDiff(prince_andrew, princess_anne).
isDiff(prince_andrew, sarah_ferguson).
isDiff(prince_andrew, sophie_rhys_jones).
isDiff(prince_andrew, kate_middleton).
isDiff(prince_andrew, autumn_kelly).
isDiff(prince_andrew, zara_phillips).
isDiff(prince_andrew, princess_beatrice).
isDiff(prince_andrew, princess_eugenie).
isDiff(prince_andrew, lady_louise_mountbatten_windsor).
isDiff(prince_andrew, princess_charlotte).
isDiff(prince_andrew, savannah_phillips).
isDiff(prince_andrew, isla_phillips).
isDiff(prince_andrew, mia_grace_tindall).
isDiff(prince_edward, prince_phillip).
isDiff(prince_edward, prince_charles).
isDiff(prince_edward, captain_mark_phillips).
isDiff(prince_edward, timothy_laurence).
isDiff(prince_edward, prince_andrew).
isDiff(prince_edward, prince_william).
isDiff(prince_edward, prince_harry).
isDiff(prince_edward, peter_phillips).
isDiff(prince_edward, mike_tindall).
isDiff(prince_edward, james_viscount_severn).
isDiff(prince_edward, prince_george).
isDiff(prince_edward, queen_elizabeth_II).
isDiff(prince_edward, princess_diana).
isDiff(prince_edward, camilla_parker_bowles).
isDiff(prince_edward, princess_anne).
isDiff(prince_edward, sarah_ferguson).
isDiff(prince_edward, sophie_rhys_jones).
isDiff(prince_edward, kate_middleton).
isDiff(prince_edward, autumn_kelly).
isDiff(prince_edward, zara_phillips).
isDiff(prince_edward, princess_beatrice).
isDiff(prince_edward, princess_eugenie).
isDiff(prince_edward, lady_louise_mountbatten_windsor).
isDiff(prince_edward, princess_charlotte).
isDiff(prince_edward, savannah_phillips).
isDiff(prince_edward, isla_phillips).
isDiff(prince_edward, mia_grace_tindall).
isDiff(prince_william, prince_phillip).
isDiff(prince_william, prince_charles).
isDiff(prince_william, captain_mark_phillips).
isDiff(prince_william, timothy_laurence).
isDiff(prince_william, prince_andrew).
isDiff(prince_william, prince_edward).
isDiff(prince_william, prince_harry).
isDiff(prince_william, peter_phillips).
isDiff(prince_william, mike_tindall).
isDiff(prince_william, james_viscount_severn).
isDiff(prince_william, prince_george).
isDiff(prince_william, queen_elizabeth_II).
isDiff(prince_william, princess_diana).
isDiff(prince_william, camilla_parker_bowles).
isDiff(prince_william, princess_anne).
isDiff(prince_william, sarah_ferguson).
isDiff(prince_william, sophie_rhys_jones).
isDiff(prince_william, kate_middleton).
isDiff(prince_william, autumn_kelly).
isDiff(prince_william, zara_phillips).
isDiff(prince_william, princess_beatrice).
isDiff(prince_william, princess_eugenie).
isDiff(prince_william, lady_louise_mountbatten_windsor).
isDiff(prince_william, princess_charlotte).
isDiff(prince_william, savannah_phillips).
isDiff(prince_william, isla_phillips).
isDiff(prince_william, mia_grace_tindall).
isDiff(prince_harry, prince_phillip).
isDiff(prince_harry, prince_charles).
isDiff(prince_harry, captain_mark_phillips).
isDiff(prince_harry, timothy_laurence).
isDiff(prince_harry, prince_andrew).
isDiff(prince_harry, prince_edward).
isDiff(prince_harry, prince_william).
isDiff(prince_harry, peter_phillips).
isDiff(prince_harry, mike_tindall).
isDiff(prince_harry, james_viscount_severn).
isDiff(prince_harry, prince_george).
isDiff(prince_harry, queen_elizabeth_II).
isDiff(prince_harry, princess_diana).
isDiff(prince_harry, camilla_parker_bowles).
isDiff(prince_harry, princess_anne).
isDiff(prince_harry, sarah_ferguson).
isDiff(prince_harry, sophie_rhys_jones).
isDiff(prince_harry, kate_middleton).
isDiff(prince_harry, autumn_kelly).
isDiff(prince_harry, zara_phillips).
isDiff(prince_harry, princess_beatrice).
isDiff(prince_harry, princess_eugenie).
isDiff(prince_harry, lady_louise_mountbatten_windsor).
isDiff(prince_harry, princess_charlotte).
isDiff(prince_harry, savannah_phillips).
isDiff(prince_harry, isla_phillips).
isDiff(prince_harry, mia_grace_tindall).
isDiff(peter_phillips, prince_phillip).
isDiff(peter_phillips, prince_charles).
isDiff(peter_phillips, captain_mark_phillips).
isDiff(peter_phillips, timothy_laurence).
isDiff(peter_phillips, prince_andrew).
isDiff(peter_phillips, prince_edward).
isDiff(peter_phillips, prince_william).
isDiff(peter_phillips, prince_harry).
isDiff(peter_phillips, mike_tindall).
isDiff(peter_phillips, james_viscount_severn).
isDiff(peter_phillips, prince_george).
isDiff(peter_phillips, queen_elizabeth_II).
isDiff(peter_phillips, princess_diana).
isDiff(peter_phillips, camilla_parker_bowles).
isDiff(peter_phillips, princess_anne).
isDiff(peter_phillips, sarah_ferguson).
isDiff(peter_phillips, sophie_rhys_jones).
isDiff(peter_phillips, kate_middleton).
isDiff(peter_phillips, autumn_kelly).
isDiff(peter_phillips, zara_phillips).
isDiff(peter_phillips, princess_beatrice).
isDiff(peter_phillips, princess_eugenie).
isDiff(peter_phillips, lady_louise_mountbatten_windsor).
isDiff(peter_phillips, princess_charlotte).
isDiff(peter_phillips, savannah_phillips).
isDiff(peter_phillips, isla_phillips).
isDiff(peter_phillips, mia_grace_tindall).
isDiff(mike_tindall, prince_phillip).
isDiff(mike_tindall, prince_charles).
isDiff(mike_tindall, captain_mark_phillips).
isDiff(mike_tindall, timothy_laurence).
isDiff(mike_tindall, prince_andrew).
isDiff(mike_tindall, prince_edward).
isDiff(mike_tindall, prince_william).
isDiff(mike_tindall, prince_harry).
isDiff(mike_tindall, peter_phillips).
isDiff(mike_tindall, james_viscount_severn).
isDiff(mike_tindall, prince_george).
isDiff(mike_tindall, queen_elizabeth_II).
isDiff(mike_tindall, princess_diana).
isDiff(mike_tindall, camilla_parker_bowles).
isDiff(mike_tindall, princess_anne).
isDiff(mike_tindall, sarah_ferguson).
isDiff(mike_tindall, sophie_rhys_jones).
isDiff(mike_tindall, kate_middleton).
isDiff(mike_tindall, autumn_kelly).
isDiff(mike_tindall, zara_phillips).
isDiff(mike_tindall, princess_beatrice).
isDiff(mike_tindall, princess_eugenie).
isDiff(mike_tindall, lady_louise_mountbatten_windsor).
isDiff(mike_tindall, princess_charlotte).
isDiff(mike_tindall, savannah_phillips).
isDiff(mike_tindall, isla_phillips).
isDiff(mike_tindall, mia_grace_tindall).
isDiff(james_viscount_severn, prince_phillip).
isDiff(james_viscount_severn, prince_charles).
isDiff(james_viscount_severn, captain_mark_phillips).
isDiff(james_viscount_severn, timothy_laurence).
isDiff(james_viscount_severn, prince_andrew).
isDiff(james_viscount_severn, prince_edward).
isDiff(james_viscount_severn, prince_william).
isDiff(james_viscount_severn, prince_harry).
isDiff(james_viscount_severn, peter_phillips).
isDiff(james_viscount_severn, mike_tindall).
isDiff(james_viscount_severn, prince_george).
isDiff(james_viscount_severn, queen_elizabeth_II).
isDiff(james_viscount_severn, princess_diana).
isDiff(james_viscount_severn, camilla_parker_bowles).
isDiff(james_viscount_severn, princess_anne).
isDiff(james_viscount_severn, sarah_ferguson).
isDiff(james_viscount_severn, sophie_rhys_jones).
isDiff(james_viscount_severn, kate_middleton).
isDiff(james_viscount_severn, autumn_kelly).
isDiff(james_viscount_severn, zara_phillips).
isDiff(james_viscount_severn, princess_beatrice).
isDiff(james_viscount_severn, princess_eugenie).
isDiff(james_viscount_severn, lady_louise_mountbatten_windsor).
isDiff(james_viscount_severn, princess_charlotte).
isDiff(james_viscount_severn, savannah_phillips).
isDiff(james_viscount_severn, isla_phillips).
isDiff(james_viscount_severn, mia_grace_tindall).
isDiff(prince_george, prince_phillip).
isDiff(prince_george, prince_charles).
isDiff(prince_george, captain_mark_phillips).
isDiff(prince_george, timothy_laurence).
isDiff(prince_george, prince_andrew).
isDiff(prince_george, prince_edward).
isDiff(prince_george, prince_william).
isDiff(prince_george, prince_harry).
isDiff(prince_george, peter_phillips).
isDiff(prince_george, mike_tindall).
isDiff(prince_george, james_viscount_severn).
isDiff(prince_george, queen_elizabeth_II).
isDiff(prince_george, princess_diana).
isDiff(prince_george, camilla_parker_bowles).
isDiff(prince_george, princess_anne).
isDiff(prince_george, sarah_ferguson).
isDiff(prince_george, sophie_rhys_jones).
isDiff(prince_george, kate_middleton).
isDiff(prince_george, autumn_kelly).
isDiff(prince_george, zara_phillips).
isDiff(prince_george, princess_beatrice).
isDiff(prince_george, princess_eugenie).
isDiff(prince_george, lady_louise_mountbatten_windsor).
isDiff(prince_george, princess_charlotte).
isDiff(prince_george, savannah_phillips).
isDiff(prince_george, isla_phillips).
isDiff(prince_george, mia_grace_tindall).
isDiff(queen_elizabeth_II, prince_phillip).
isDiff(queen_elizabeth_II, prince_charles).
isDiff(queen_elizabeth_II, captain_mark_phillips).
isDiff(queen_elizabeth_II, timothy_laurence).
isDiff(queen_elizabeth_II, prince_andrew).
isDiff(queen_elizabeth_II, prince_edward).
isDiff(queen_elizabeth_II, prince_william).
isDiff(queen_elizabeth_II, prince_harry).
isDiff(queen_elizabeth_II, peter_phillips).
isDiff(queen_elizabeth_II, mike_tindall).
isDiff(queen_elizabeth_II, james_viscount_severn).
isDiff(queen_elizabeth_II, prince_george).
isDiff(queen_elizabeth_II, princess_diana).
isDiff(queen_elizabeth_II, camilla_parker_bowles).
isDiff(queen_elizabeth_II, princess_anne).
isDiff(queen_elizabeth_II, sarah_ferguson).
isDiff(queen_elizabeth_II, sophie_rhys_jones).
isDiff(queen_elizabeth_II, kate_middleton).
isDiff(queen_elizabeth_II, autumn_kelly).
isDiff(queen_elizabeth_II, zara_phillips).
isDiff(queen_elizabeth_II, princess_beatrice).
isDiff(queen_elizabeth_II, princess_eugenie).
isDiff(queen_elizabeth_II, lady_louise_mountbatten_windsor).
isDiff(queen_elizabeth_II, princess_charlotte).
isDiff(queen_elizabeth_II, savannah_phillips).
isDiff(queen_elizabeth_II, isla_phillips).
isDiff(queen_elizabeth_II, mia_grace_tindall).
isDiff(princess_diana, prince_phillip).
isDiff(princess_diana, prince_charles).
isDiff(princess_diana, captain_mark_phillips).
isDiff(princess_diana, timothy_laurence).
isDiff(princess_diana, prince_andrew).
isDiff(princess_diana, prince_edward).
isDiff(princess_diana, prince_william).
isDiff(princess_diana, prince_harry).
isDiff(princess_diana, peter_phillips).
isDiff(princess_diana, mike_tindall).
isDiff(princess_diana, james_viscount_severn).
isDiff(princess_diana, prince_george).
isDiff(princess_diana, queen_elizabeth_II).
isDiff(princess_diana, camilla_parker_bowles).
isDiff(princess_diana, princess_anne).
isDiff(princess_diana, sarah_ferguson).
isDiff(princess_diana, sophie_rhys_jones).
isDiff(princess_diana, kate_middleton).
isDiff(princess_diana, autumn_kelly).
isDiff(princess_diana, zara_phillips).
isDiff(princess_diana, princess_beatrice).
isDiff(princess_diana, princess_eugenie).
isDiff(princess_diana, lady_louise_mountbatten_windsor).
isDiff(princess_diana, princess_charlotte).
isDiff(princess_diana, savannah_phillips).
isDiff(princess_diana, isla_phillips).
isDiff(princess_diana, mia_grace_tindall).
isDiff(camilla_parker_bowles, prince_phillip).
isDiff(camilla_parker_bowles, prince_charles).
isDiff(camilla_parker_bowles, captain_mark_phillips).
isDiff(camilla_parker_bowles, timothy_laurence).
isDiff(camilla_parker_bowles, prince_andrew).
isDiff(camilla_parker_bowles, prince_edward).
isDiff(camilla_parker_bowles, prince_william).
isDiff(camilla_parker_bowles, prince_harry).
isDiff(camilla_parker_bowles, peter_phillips).
isDiff(camilla_parker_bowles, mike_tindall).
isDiff(camilla_parker_bowles, james_viscount_severn).
isDiff(camilla_parker_bowles, prince_george).
isDiff(camilla_parker_bowles, queen_elizabeth_II).
isDiff(camilla_parker_bowles, princess_diana).
isDiff(camilla_parker_bowles, princess_anne).
isDiff(camilla_parker_bowles, sarah_ferguson).
isDiff(camilla_parker_bowles, sophie_rhys_jones).
isDiff(camilla_parker_bowles, kate_middleton).
isDiff(camilla_parker_bowles, autumn_kelly).
isDiff(camilla_parker_bowles, zara_phillips).
isDiff(camilla_parker_bowles, princess_beatrice).
isDiff(camilla_parker_bowles, princess_eugenie).
isDiff(camilla_parker_bowles, lady_louise_mountbatten_windsor).
isDiff(camilla_parker_bowles, princess_charlotte).
isDiff(camilla_parker_bowles, savannah_phillips).
isDiff(camilla_parker_bowles, isla_phillips).
isDiff(camilla_parker_bowles, mia_grace_tindall).
isDiff(princess_anne, prince_phillip).
isDiff(princess_anne, prince_charles).
isDiff(princess_anne, captain_mark_phillips).
isDiff(princess_anne, timothy_laurence).
isDiff(princess_anne, prince_andrew).
isDiff(princess_anne, prince_edward).
isDiff(princess_anne, prince_william).
isDiff(princess_anne, prince_harry).
isDiff(princess_anne, peter_phillips).
isDiff(princess_anne, mike_tindall).
isDiff(princess_anne, james_viscount_severn).
isDiff(princess_anne, prince_george).
isDiff(princess_anne, queen_elizabeth_II).
isDiff(princess_anne, princess_diana).
isDiff(princess_anne, camilla_parker_bowles).
isDiff(princess_anne, sarah_ferguson).
isDiff(princess_anne, sophie_rhys_jones).
isDiff(princess_anne, kate_middleton).
isDiff(princess_anne, autumn_kelly).
isDiff(princess_anne, zara_phillips).
isDiff(princess_anne, princess_beatrice).
isDiff(princess_anne, princess_eugenie).
isDiff(princess_anne, lady_louise_mountbatten_windsor).
isDiff(princess_anne, princess_charlotte).
isDiff(princess_anne, savannah_phillips).
isDiff(princess_anne, isla_phillips).
isDiff(princess_anne, mia_grace_tindall).
isDiff(sarah_ferguson, prince_phillip).
isDiff(sarah_ferguson, prince_charles).
isDiff(sarah_ferguson, captain_mark_phillips).
isDiff(sarah_ferguson, timothy_laurence).
isDiff(sarah_ferguson, prince_andrew).
isDiff(sarah_ferguson, prince_edward).
isDiff(sarah_ferguson, prince_william).
isDiff(sarah_ferguson, prince_harry).
isDiff(sarah_ferguson, peter_phillips).
isDiff(sarah_ferguson, mike_tindall).
isDiff(sarah_ferguson, james_viscount_severn).
isDiff(sarah_ferguson, prince_george).
isDiff(sarah_ferguson, queen_elizabeth_II).
isDiff(sarah_ferguson, princess_diana).
isDiff(sarah_ferguson, camilla_parker_bowles).
isDiff(sarah_ferguson, princess_anne).
isDiff(sarah_ferguson, sophie_rhys_jones).
isDiff(sarah_ferguson, kate_middleton).
isDiff(sarah_ferguson, autumn_kelly).
isDiff(sarah_ferguson, zara_phillips).
isDiff(sarah_ferguson, princess_beatrice).
isDiff(sarah_ferguson, princess_eugenie).
isDiff(sarah_ferguson, lady_louise_mountbatten_windsor).
isDiff(sarah_ferguson, princess_charlotte).
isDiff(sarah_ferguson, savannah_phillips).
isDiff(sarah_ferguson, isla_phillips).
isDiff(sarah_ferguson, mia_grace_tindall).
isDiff(sophie_rhys_jones, prince_phillip).
isDiff(sophie_rhys_jones, prince_charles).
isDiff(sophie_rhys_jones, captain_mark_phillips).
isDiff(sophie_rhys_jones, timothy_laurence).
isDiff(sophie_rhys_jones, prince_andrew).
isDiff(sophie_rhys_jones, prince_edward).
isDiff(sophie_rhys_jones, prince_william).
isDiff(sophie_rhys_jones, prince_harry).
isDiff(sophie_rhys_jones, peter_phillips).
isDiff(sophie_rhys_jones, mike_tindall).
isDiff(sophie_rhys_jones, james_viscount_severn).
isDiff(sophie_rhys_jones, prince_george).
isDiff(sophie_rhys_jones, queen_elizabeth_II).
isDiff(sophie_rhys_jones, princess_diana).
isDiff(sophie_rhys_jones, camilla_parker_bowles).
isDiff(sophie_rhys_jones, princess_anne).
isDiff(sophie_rhys_jones, sarah_ferguson).
isDiff(sophie_rhys_jones, kate_middleton).
isDiff(sophie_rhys_jones, autumn_kelly).
isDiff(sophie_rhys_jones, zara_phillips).
isDiff(sophie_rhys_jones, princess_beatrice).
isDiff(sophie_rhys_jones, princess_eugenie).
isDiff(sophie_rhys_jones, lady_louise_mountbatten_windsor).
isDiff(sophie_rhys_jones, princess_charlotte).
isDiff(sophie_rhys_jones, savannah_phillips).
isDiff(sophie_rhys_jones, isla_phillips).
isDiff(sophie_rhys_jones, mia_grace_tindall).
isDiff(kate_middleton, prince_phillip).
isDiff(kate_middleton, prince_charles).
isDiff(kate_middleton, captain_mark_phillips).
isDiff(kate_middleton, timothy_laurence).
isDiff(kate_middleton, prince_andrew).
isDiff(kate_middleton, prince_edward).
isDiff(kate_middleton, prince_william).
isDiff(kate_middleton, prince_harry).
isDiff(kate_middleton, peter_phillips).
isDiff(kate_middleton, mike_tindall).
isDiff(kate_middleton, james_viscount_severn).
isDiff(kate_middleton, prince_george).
isDiff(kate_middleton, queen_elizabeth_II).
isDiff(kate_middleton, princess_diana).
isDiff(kate_middleton, camilla_parker_bowles).
isDiff(kate_middleton, princess_anne).
isDiff(kate_middleton, sarah_ferguson).
isDiff(kate_middleton, sophie_rhys_jones).
isDiff(kate_middleton, autumn_kelly).
isDiff(kate_middleton, zara_phillips).
isDiff(kate_middleton, princess_beatrice).
isDiff(kate_middleton, princess_eugenie).
isDiff(kate_middleton, lady_louise_mountbatten_windsor).
isDiff(kate_middleton, princess_charlotte).
isDiff(kate_middleton, savannah_phillips).
isDiff(kate_middleton, isla_phillips).
isDiff(kate_middleton, mia_grace_tindall).
isDiff(autumn_kelly, prince_phillip).
isDiff(autumn_kelly, prince_charles).
isDiff(autumn_kelly, captain_mark_phillips).
isDiff(autumn_kelly, timothy_laurence).
isDiff(autumn_kelly, prince_andrew).
isDiff(autumn_kelly, prince_edward).
isDiff(autumn_kelly, prince_william).
isDiff(autumn_kelly, prince_harry).
isDiff(autumn_kelly, peter_phillips).
isDiff(autumn_kelly, mike_tindall).
isDiff(autumn_kelly, james_viscount_severn).
isDiff(autumn_kelly, prince_george).
isDiff(autumn_kelly, queen_elizabeth_II).
isDiff(autumn_kelly, princess_diana).
isDiff(autumn_kelly, camilla_parker_bowles).
isDiff(autumn_kelly, princess_anne).
isDiff(autumn_kelly, sarah_ferguson).
isDiff(autumn_kelly, sophie_rhys_jones).
isDiff(autumn_kelly, kate_middleton).
isDiff(autumn_kelly, zara_phillips).
isDiff(autumn_kelly, princess_beatrice).
isDiff(autumn_kelly, princess_eugenie).
isDiff(autumn_kelly, lady_louise_mountbatten_windsor).
isDiff(autumn_kelly, princess_charlotte).
isDiff(autumn_kelly, savannah_phillips).
isDiff(autumn_kelly, isla_phillips).
isDiff(autumn_kelly, mia_grace_tindall).
isDiff(zara_phillips, prince_phillip).
isDiff(zara_phillips, prince_charles).
isDiff(zara_phillips, captain_mark_phillips).
isDiff(zara_phillips, timothy_laurence).
isDiff(zara_phillips, prince_andrew).
isDiff(zara_phillips, prince_edward).
isDiff(zara_phillips, prince_william).
isDiff(zara_phillips, prince_harry).
isDiff(zara_phillips, peter_phillips).
isDiff(zara_phillips, mike_tindall).
isDiff(zara_phillips, james_viscount_severn).
isDiff(zara_phillips, prince_george).
isDiff(zara_phillips, queen_elizabeth_II).
isDiff(zara_phillips, princess_diana).
isDiff(zara_phillips, camilla_parker_bowles).
isDiff(zara_phillips, princess_anne).
isDiff(zara_phillips, sarah_ferguson).
isDiff(zara_phillips, sophie_rhys_jones).
isDiff(zara_phillips, kate_middleton).
isDiff(zara_phillips, autumn_kelly).
isDiff(zara_phillips, princess_beatrice).
isDiff(zara_phillips, princess_eugenie).
isDiff(zara_phillips, lady_louise_mountbatten_windsor).
isDiff(zara_phillips, princess_charlotte).
isDiff(zara_phillips, savannah_phillips).
isDiff(zara_phillips, isla_phillips).
isDiff(zara_phillips, mia_grace_tindall).
isDiff(princess_beatrice, prince_phillip).
isDiff(princess_beatrice, prince_charles).
isDiff(princess_beatrice, captain_mark_phillips).
isDiff(princess_beatrice, timothy_laurence).
isDiff(princess_beatrice, prince_andrew).
isDiff(princess_beatrice, prince_edward).
isDiff(princess_beatrice, prince_william).
isDiff(princess_beatrice, prince_harry).
isDiff(princess_beatrice, peter_phillips).
isDiff(princess_beatrice, mike_tindall).
isDiff(princess_beatrice, james_viscount_severn).
isDiff(princess_beatrice, prince_george).
isDiff(princess_beatrice, queen_elizabeth_II).
isDiff(princess_beatrice, princess_diana).
isDiff(princess_beatrice, camilla_parker_bowles).
isDiff(princess_beatrice, princess_anne).
isDiff(princess_beatrice, sarah_ferguson).
isDiff(princess_beatrice, sophie_rhys_jones).
isDiff(princess_beatrice, kate_middleton).
isDiff(princess_beatrice, autumn_kelly).
isDiff(princess_beatrice, zara_phillips).
isDiff(princess_beatrice, princess_eugenie).
isDiff(princess_beatrice, lady_louise_mountbatten_windsor).
isDiff(princess_beatrice, princess_charlotte).
isDiff(princess_beatrice, savannah_phillips).
isDiff(princess_beatrice, isla_phillips).
isDiff(princess_beatrice, mia_grace_tindall).
isDiff(princess_eugenie, prince_phillip).
isDiff(princess_eugenie, prince_charles).
isDiff(princess_eugenie, captain_mark_phillips).
isDiff(princess_eugenie, timothy_laurence).
isDiff(princess_eugenie, prince_andrew).
isDiff(princess_eugenie, prince_edward).
isDiff(princess_eugenie, prince_william).
isDiff(princess_eugenie, prince_harry).
isDiff(princess_eugenie, peter_phillips).
isDiff(princess_eugenie, mike_tindall).
isDiff(princess_eugenie, james_viscount_severn).
isDiff(princess_eugenie, prince_george).
isDiff(princess_eugenie, queen_elizabeth_II).
isDiff(princess_eugenie, princess_diana).
isDiff(princess_eugenie, camilla_parker_bowles).
isDiff(princess_eugenie, princess_anne).
isDiff(princess_eugenie, sarah_ferguson).
isDiff(princess_eugenie, sophie_rhys_jones).
isDiff(princess_eugenie, kate_middleton).
isDiff(princess_eugenie, autumn_kelly).
isDiff(princess_eugenie, zara_phillips).
isDiff(princess_eugenie, princess_beatrice).
isDiff(princess_eugenie, lady_louise_mountbatten_windsor).
isDiff(princess_eugenie, princess_charlotte).
isDiff(princess_eugenie, savannah_phillips).
isDiff(princess_eugenie, isla_phillips).
isDiff(princess_eugenie, mia_grace_tindall).
isDiff(lady_louise_mountbatten_windsor, prince_phillip).
isDiff(lady_louise_mountbatten_windsor, prince_charles).
isDiff(lady_louise_mountbatten_windsor, captain_mark_phillips).
isDiff(lady_louise_mountbatten_windsor, timothy_laurence).
isDiff(lady_louise_mountbatten_windsor, prince_andrew).
isDiff(lady_louise_mountbatten_windsor, prince_edward).
isDiff(lady_louise_mountbatten_windsor, prince_william).
isDiff(lady_louise_mountbatten_windsor, prince_harry).
isDiff(lady_louise_mountbatten_windsor, peter_phillips).
isDiff(lady_louise_mountbatten_windsor, mike_tindall).
isDiff(lady_louise_mountbatten_windsor, james_viscount_severn).
isDiff(lady_louise_mountbatten_windsor, prince_george).
isDiff(lady_louise_mountbatten_windsor, queen_elizabeth_II).
isDiff(lady_louise_mountbatten_windsor, princess_diana).
isDiff(lady_louise_mountbatten_windsor, camilla_parker_bowles).
isDiff(lady_louise_mountbatten_windsor, princess_anne).
isDiff(lady_louise_mountbatten_windsor, sarah_ferguson).
isDiff(lady_louise_mountbatten_windsor, sophie_rhys_jones).
isDiff(lady_louise_mountbatten_windsor, kate_middleton).
isDiff(lady_louise_mountbatten_windsor, autumn_kelly).
isDiff(lady_louise_mountbatten_windsor, zara_phillips).
isDiff(lady_louise_mountbatten_windsor, princess_beatrice).
isDiff(lady_louise_mountbatten_windsor, princess_eugenie).
isDiff(lady_louise_mountbatten_windsor, princess_charlotte).
isDiff(lady_louise_mountbatten_windsor, savannah_phillips).
isDiff(lady_louise_mountbatten_windsor, isla_phillips).
isDiff(lady_louise_mountbatten_windsor, mia_grace_tindall).
isDiff(princess_charlotte, prince_phillip).
isDiff(princess_charlotte, prince_charles).
isDiff(princess_charlotte, captain_mark_phillips).
isDiff(princess_charlotte, timothy_laurence).
isDiff(princess_charlotte, prince_andrew).
isDiff(princess_charlotte, prince_edward).
isDiff(princess_charlotte, prince_william).
isDiff(princess_charlotte, prince_harry).
isDiff(princess_charlotte, peter_phillips).
isDiff(princess_charlotte, mike_tindall).
isDiff(princess_charlotte, james_viscount_severn).
isDiff(princess_charlotte, prince_george).
isDiff(princess_charlotte, queen_elizabeth_II).
isDiff(princess_charlotte, princess_diana).
isDiff(princess_charlotte, camilla_parker_bowles).
isDiff(princess_charlotte, princess_anne).
isDiff(princess_charlotte, sarah_ferguson).
isDiff(princess_charlotte, sophie_rhys_jones).
isDiff(princess_charlotte, kate_middleton).
isDiff(princess_charlotte, autumn_kelly).
isDiff(princess_charlotte, zara_phillips).
isDiff(princess_charlotte, princess_beatrice).
isDiff(princess_charlotte, princess_eugenie).
isDiff(princess_charlotte, lady_louise_mountbatten_windsor).
isDiff(princess_charlotte, savannah_phillips).
isDiff(princess_charlotte, isla_phillips).
isDiff(princess_charlotte, mia_grace_tindall).
isDiff(savannah_phillips, prince_phillip).
isDiff(savannah_phillips, prince_charles).
isDiff(savannah_phillips, captain_mark_phillips).
isDiff(savannah_phillips, timothy_laurence).
isDiff(savannah_phillips, prince_andrew).
isDiff(savannah_phillips, prince_edward).
isDiff(savannah_phillips, prince_william).
isDiff(savannah_phillips, prince_harry).
isDiff(savannah_phillips, peter_phillips).
isDiff(savannah_phillips, mike_tindall).
isDiff(savannah_phillips, james_viscount_severn).
isDiff(savannah_phillips, prince_george).
isDiff(savannah_phillips, queen_elizabeth_II).
isDiff(savannah_phillips, princess_diana).
isDiff(savannah_phillips, camilla_parker_bowles).
isDiff(savannah_phillips, princess_anne).
isDiff(savannah_phillips, sarah_ferguson).
isDiff(savannah_phillips, sophie_rhys_jones).
isDiff(savannah_phillips, kate_middleton).
isDiff(savannah_phillips, autumn_kelly).
isDiff(savannah_phillips, zara_phillips).
isDiff(savannah_phillips, princess_beatrice).
isDiff(savannah_phillips, princess_eugenie).
isDiff(savannah_phillips, lady_louise_mountbatten_windsor).
isDiff(savannah_phillips, princess_charlotte).
isDiff(savannah_phillips, isla_phillips).
isDiff(savannah_phillips, mia_grace_tindall).
isDiff(isla_phillips, prince_phillip).
isDiff(isla_phillips, prince_charles).
isDiff(isla_phillips, captain_mark_phillips).
isDiff(isla_phillips, timothy_laurence).
isDiff(isla_phillips, prince_andrew).
isDiff(isla_phillips, prince_edward).
isDiff(isla_phillips, prince_william).
isDiff(isla_phillips, prince_harry).
isDiff(isla_phillips, peter_phillips).
isDiff(isla_phillips, mike_tindall).
isDiff(isla_phillips, james_viscount_severn).
isDiff(isla_phillips, prince_george).
isDiff(isla_phillips, queen_elizabeth_II).
isDiff(isla_phillips, princess_diana).
isDiff(isla_phillips, camilla_parker_bowles).
isDiff(isla_phillips, princess_anne).
isDiff(isla_phillips, sarah_ferguson).
isDiff(isla_phillips, sophie_rhys_jones).
isDiff(isla_phillips, kate_middleton).
isDiff(isla_phillips, autumn_kelly).
isDiff(isla_phillips, zara_phillips).
isDiff(isla_phillips, princess_beatrice).
isDiff(isla_phillips, princess_eugenie).
isDiff(isla_phillips, lady_louise_mountbatten_windsor).
isDiff(isla_phillips, princess_charlotte).
isDiff(isla_phillips, savannah_phillips).
isDiff(isla_phillips, mia_grace_tindall).
isDiff(mia_grace_tindall, prince_phillip).
isDiff(mia_grace_tindall, prince_charles).
isDiff(mia_grace_tindall, captain_mark_phillips).
isDiff(mia_grace_tindall, timothy_laurence).
isDiff(mia_grace_tindall, prince_andrew).
isDiff(mia_grace_tindall, prince_edward).
isDiff(mia_grace_tindall, prince_william).
isDiff(mia_grace_tindall, prince_harry).
isDiff(mia_grace_tindall, peter_phillips).
isDiff(mia_grace_tindall, mike_tindall).
isDiff(mia_grace_tindall, james_viscount_severn).
isDiff(mia_grace_tindall, prince_george).
isDiff(mia_grace_tindall, queen_elizabeth_II).
isDiff(mia_grace_tindall, princess_diana).
isDiff(mia_grace_tindall, camilla_parker_bowles).
isDiff(mia_grace_tindall, princess_anne).
isDiff(mia_grace_tindall, sarah_ferguson).
isDiff(mia_grace_tindall, sophie_rhys_jones).
isDiff(mia_grace_tindall, kate_middleton).
isDiff(mia_grace_tindall, autumn_kelly).
isDiff(mia_grace_tindall, zara_phillips).
isDiff(mia_grace_tindall, princess_beatrice).
isDiff(mia_grace_tindall, princess_eugenie).
isDiff(mia_grace_tindall, lady_louise_mountbatten_windsor).
isDiff(mia_grace_tindall, princess_charlotte).
isDiff(mia_grace_tindall, savannah_phillips).
isDiff(mia_grace_tindall, isla_phillips).

/* Gender */
male(prince_phillip).
male(prince_charles).
male(captain_mark_phillips).
male(timothy_laurence).
male(prince_andrew).
male(prince_edward).
male(prince_william).
male(prince_harry).
male(peter_phillips).
male(mike_tindall).
male(james_viscount_severn).
male(prince_george).

female(queen_elizabeth_II).
female(princess_diana).
female(camilla_parker_bowles).
female(princess_anne).
female(sarah_ferguson).
female(sophie_rhys_jones).
female(kate_middleton).
female(autumn_kelly).
female(zara_phillips).
female(princess_beatrice).
female(princess_eugenie).
female(lady_louise_mountbatten_windsor).
female(princess_charlotte).
female(savannah_phillips).
female(isla_phillips).
female(mia_grace_tindall).

/* Marital status*/
married(queen_elizabeth_II, prince_phillip).
married(prince_phillip,queen_elizabeth_II).
married(prince_charles, camilla_parker_bowles).
married(camilla_parker_bowles, prince_charles).
married(princess_anne, timothy_laurence).
married(timothy_laurence, princess_anne).
married(prince_edward, sophie_rhys_jones).
married(sophie_rhys_jones, prince_edward).
married(prince_william, kate_middleton).
married(kate_middleton, prince_william).
married(autumn_kelly, peter_phillips).
married(peter_phillips, autumn_kelly).
married(zara_phillips, mike_tindall).
married(mike_tindall, zara_phillips).

divorced(princess_diana, prince_charles).
divorced(prince_charles, princess_diana).
divorced(captain_mark_phillips, princess_anne).
divorced(princess_anne, captain_mark_phillips).
divorced(princess_andrew, sarah_ferguson).
divorced(sarah_ferguson, princess_andrew).


/* Family relationship */
parent(queen_elizabeth_II, prince_charles).
parent(prince_phillip, prince_charles).
parent(queen_elizabeth_II, prince_andrew).
parent(prince_phillip, prince_andrew).
parent(queen_elizabeth_II, princess_anne).
parent(prince_phillip, princess_anne).
parent(queen_elizabeth_II, prince_edward).
parent(prince_phillip, prince_edward).

parent(princess_diana, prince_william).
parent(prince_charles, prince_william).
parent(princess_diana, prince_harry).
parent(prince_charles, prince_harry).

parent(princess_anne, peter_phillips).
parent(captain_mark_phillips, peter_phillips).
parent(princess_anne, zara_phillips).
parent(captain_mark_phillips, zara_phillips).

parent(sarah_ferguson, princess_beatrice).
parent(prince_andrew, princess_beatrice).
parent(sarah_ferguson, princess_eugenie).
parent(prince_andrew, princess_eugenie).

parent(sophie_rhys_jones, james_viscount_severn).
parent(prince_edward, james_viscount_severn).
parent(sophie_rhys_jones, lady_louise_mountbatten_windsor).
parent(prince_edward, lady_louise_mountbatten_windsor).

parent(kate_middleton, prince_george).
parent(prince_william, prince_george).
parent(kate_middleton, princess_charlotte).
parent(prince_william, princess_charlotte).

parent(autumn_kelly,savannah_phillips).
parent(peter_phillips,savannah_phillips).
parent(autumn_kelly,isla_phillips).
parent(peter_phillips,isla_phillips).

parent(zara_phillips, mia_grace_tindall).
parent(mike_tindall, mia_grace_tindall).


/* Rules */
husband(Person,Wife) :- married(Person,Wife), male(Person), female(Wife).
wife(Person,Husband) :- married(Person,Husband), male(Husband), female(Person).

father(Parent,Child) :- parent(Parent,Child), male(Parent).
mother(Parent,Child) :- parent(Parent,Child), female(Parent).

child(Child,Parent) :- parent(Parent,Child).
son(Child,Parent) :- child(Child,Parent), male(Child).
daughter(Child,Parent) :- child(Child,Parent), female(Child).

grandparent(GP,GC) :- parent(GP,Parent), parent(Parent,GC).
grandmother(GM,GC) :- grandparent(GM,GC), female(GM).
grandfather(GF,GC) :- grandparent(GF,GC), male(GF).

grandchild(GC,GP) :- grandparent(GP,GC).
grandson(GS,GP) :- grandchild(GS,GP),male(GS).
granddaughter(GD,GP) :- grandchild(GD,GP), female(GD).
 

sibling(Person1,Person2) :- parent(X,Person1), parent(X,Person2), isDiff(Person1,Person2).
brother(Person,Sibling) :- sibling(Person, Sibling), male(Person).
sister(Person,Sibling) :- sibling(Person, Sibling), female(Person).

aunt(Person, NieceNephew) :- parent(Person1,NieceNephew), parent(Person2,Person),parent(Person2,Person1),female(Person),isDiff(Person1,Person).

uncle(Person, NieceNephew) :- parent(Person1,NieceNephew), parent(Person2,Person),parent(Person2,Person1),male(Person), isDiff(Person1,Person).

niece(Person, AuntUncle) :- parent(Person1,Person), parent(Person2,AuntUncle),parent(Person2,Person1),female(Person), isDiff(Person1,AuntUncle).

nephew(Person, AuntUncle) :- parent(Person1,Person), parent(Person2,AuntUncle),parent(Person2,Person1),male(Person), isDiff(Person1,AuntUncle).